# Python Runtime
FROM python:3.11-slim

# Prevent Python from writing .pyc files & enable unbuffered logging
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy runtime dependencies definition
COPY requirements-docker.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy fastapi backend only leaving notebooks/, datasets/ , scripts/ , tests/ 
COPY config.py ./config.py
COPY app/ ./app/
COPY models/ ./models/

EXPOSE 8000

# Run FastAPI server using python , for more workers need of uvicon or gvicorn
CMD ["python","-m","app.main"]


